chore: Update tests (#54)
Signed-off-by: Steve Hipwell <steve.hipwell@gmail.com>

diff --git a/.github/workflows/validate.yaml b/.github/workflows/validate.yaml
--- a/.github/workflows/validate.yaml
+++ b/.github/workflows/validate.yaml
@@ -84,8 +84,12 @@ jobs:
 
       - name: Check diff
         run: |
-          git diff --compact-summary --exit-code || \
-            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
+          set -euo pipefail
+
+          if [[ -n "$(git status --porcelain)" ]]; then
+            echo "::error::Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."
+            exit 1
+          fi
 
   matrix:
     name: Matrix
